CREATE TABLE dermaga(
   id         INTEGER  NOT NULL PRIMARY KEY 
  ,kdCabang   INTEGER  NOT NULL
  ,mdmgKode   VARCHAR(7) NOT NULL
  ,mdmgNama   VARCHAR(30) NOT NULL
  ,kdTerminal INTEGER 
);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (1,2,'37','LAMONG OCEAN GOING',10);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (2,2,'38','LAMONG NUSANTARA',10);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (3,2,'31','REDE DOK GRESIK',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (4,2,'6','ZONA LABUH 1 (REDE SURABAYA)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (5,2,'11','BERLIAN UTARA',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (6,2,'7','JAMRUD UTARA',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (7,2,'8','JAMRUD SELATAN',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (8,2,'9','JAMRUD BARAT',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (9,2,'10','KADE PERAK',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (10,2,'22','SEMAMPIR',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (11,2,'30','TPS/ICT OCEAN GOING',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (12,2,'12','BERLIAN BARAT',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (13,2,'13','BERLIAN TIMUR / BEACHING',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (14,2,'15','KADE INTAN',2);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (15,2,'17','NILAM TIMUR',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (16,2,'21','GOSSPIER',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (17,2,'51','BOGASARI',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (18,2,'52','PINDA ASEN',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (19,2,'14','TAMBATAN MIRAH',2);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (20,2,'20','TAMBATAN KALIMAS',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (21,2,'1','JAMUANG/AMBANG LUAR',2);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (22,2,'33','ICT NUSANTARA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (23,2,'55','MASPION',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (24,2,'56','SMELTING',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (25,2,'3','ZONA LABUH 4 (REDE GRESIK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (26,2,'4','KADE GRESIK',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (27,2,'5','PETROKIMIA',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (28,2,'16','DERMAGA P3/DISNAV',2);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (29,2,'23','DOCK SURABAYA',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (30,2,'24','GRVING DOCK/PAL',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (31,2,'27','DERMAGA MADURA/UJUNG ARMADA',1);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (32,2,'28','DOCK PENGERUKAN',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (33,2,'19','KALI PERAK/NILAM BARAT',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (34,2,'2','ALUR TIMUR',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (35,2,'40','PROBOLINGGO',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (36,2,'34','DOK GRESIK',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (37,2,'35','KADE PLTU GRESIK',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (38,2,'77','BRANTA',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (39,2,'88','TUBAN',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (40,2,'44','PASURUAN',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (41,2,'80','REDE LAUT TUBAN',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (42,2,'70','REDE LAUT BRANTA',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (43,2,'41','REDE LAUT PASURUAN',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (44,2,'36','WILMAR',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (45,2,'25','REDE DOCK',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (46,11,'RT','AREA KHUSUS LABUH',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (47,11,'11','YETTY I AREA 70',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (48,11,'4','TAMBATAN II',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (49,11,'1','OUTBAR',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (50,11,'8','YETTY PDN',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (51,11,'26','SMALL CRAF',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (52,11,'34','PINGGIRAN',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (53,11,'14','JETTY CIB I',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (54,11,'29','UJUNG J. III/ 70',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (55,11,'3','TAMBATAN I',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (56,11,'5','TAMBATAN III',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (57,11,'6','TAMBATAN IV',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (58,11,'7','WIJAYA PURA',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (59,11,'2','REDE',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (60,11,'9','YETTY PUSRI',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (61,11,'10','TAMB. KARANG TALUN II',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (62,11,'12','YETTY II AREA 70',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (63,11,'13','YETTY III AREA 70',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (64,11,'15','YETTY CIB II',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (65,11,'16','TAMBATAN VI',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (66,11,'17','YETTY PASIR BESI',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (67,11,'18','YETTY DONAN I AREA 60',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (68,11,'20','YETTY DONAN III AREA 60',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (69,11,'25','TAMB. PERHUTANI',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (70,11,'27','POSISI LABUH',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (71,11,'28','BUOY RIPER',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (72,11,'SPM01','SPM PERTAMINA',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (73,11,'19','YETTY DONAN II AREA 60',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (74,11,'30','DERMAGA PLTU',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (75,11,'31','DLKR PELABUHAN',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (76,11,'37','REDE PLTU',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (77,11,'36','TAMB. KARANG TALUN I',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (78,11,'35','NUSAKAMBANGAN',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (79,24,'51','DERMAGA UMUM PULPIS',27);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (80,24,'52','DERMAGA PINGGIRAN PULPIS',27);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (81,24,'8','KADE TRISAKTI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (82,24,'10','KADE MARTAPURA BARU',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (83,24,'11','KADE AKR',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (84,24,'12','KADE KUIN',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (85,24,'13','KADE TSJM/JELAPAT LUAR',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (86,24,'14','KADE TANJUNG RAYA/P.BROMO',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (87,24,'15','KADE PT.BERSAMA',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (88,24,'16','KADE DAYA SAKTI/B.RAYA/A.YANI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (89,24,'17','KADE PULAU BAKUT',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (90,24,'19','KADE BASIRIH',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (91,24,'23','KADE DAYA SAKTI JELAPAT',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (92,24,'24','KADE BARITO PASIFIK JELAPAT',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (93,24,'25','KADE GUCHI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (94,25,'DGOLHOP','DERMAGA PT, GOLDEN HOPE',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (95,25,'OB','OUTBAR PEMANCINGAN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (96,25,'2','NPLCT TJ. PEMANCINGAN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (97,25,'3','DERMAGA AIR TAWAR II',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (98,25,'4','DERMAGA PANJANG KOTABARU',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (99,25,'6','DERMAGA PT. MISAJA MITRA',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (100,25,'7','DERMAGA PT. ITP TARJUN',57);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (101,25,'9','DERMAGA PT. INHUTANI STAGEN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (102,25,'RK','REDE KOTABARU',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (103,25,'10','DERMAGA SELARU',56);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (104,25,'12','DERMAGA KBN',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (105,25,'13','DERMAGA KODECO',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (106,25,'15','DERMAGA LIANG ANGGANG',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (107,25,'10','REDE BATULICIN',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (108,25,'13','REDE/MUARA PGT/TG.PETANG',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (109,25,'20','REDE SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (110,25,'7','REDE SELARU/SEI PINANG',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (111,25,'5','REDE STAGEN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (112,25,'16','DERMAGA IBT',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (113,25,'17','DERMAGA PAGATAN',54);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (114,25,'18','DERMAGA SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (115,25,'27','REDE TG. MANGKOK',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (116,25,'8','DERMAGA PERTAMINA',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (117,25,'11','DERMAGA BATULICIN 1',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (118,25,'14','DERMAGA PARLIN',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (119,25,'5','DERMAGA STAGEN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (120,25,'19','OUTBAR TG. PEMANCINGAN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (121,25,'20','OUTBAR TG. PETANG',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (122,25,'21','REDE KOTABARU/DUKS',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (123,25,'22','REDE TANJUNG MANGKOK',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (124,25,'23','DERMAGA ASDP',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (125,25,'3','REDE TG. PEMANCINGAN',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (126,25,'1','DERMAGA AIR TAWAR I',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (127,25,'24','REDE SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (128,25,'2','REDE TARJUN',57);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (129,25,'101','PINGGIRAN KOTABARU',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (130,25,'18','REDE MEKARPUTIH',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (131,25,'RT','REDE TRANSHIPMENT',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (132,25,'BCM','DERMAGA BCM',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (133,25,'CHU','PT. CAHAYA UJUNG',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (134,25,'ALE','PT. MANGIUM ANUGERAH LESTARI',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (135,25,'MGM','REDE ALE ALE',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (136,25,'SMART','REDE SMART',57);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (137,25,'DSMART','DERMAGA SMART',57);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (138,25,'BUN','REDE BUNATI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (139,29,'35','DERMAGA LNB',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (140,29,'44','DERMAGA KHUSUS KUALA PEMBUANG',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (141,29,'10','SURYA MENTAYA,CV',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (142,12,'2','DERMAGA SELATAN',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (143,12,'3','DERMAGA BARAT',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (144,12,'DK','DERMAGA BUMI PASIR',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (145,12,'PT','DERMAGA PERTAMINA',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (146,12,'K1','DERMAGA PSB',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (147,12,'RD','REDE',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (148,12,'OB','OUTER BOUY',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (149,12,'TD','TENDER',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (150,12,'DM','DERMAGA MABUA',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (151,12,'DB','DERMAGA BALI HAI',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (152,12,'BC','DERMAGA BOUNTY',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (153,12,'DQ','DERMAGA QUICK SILVER',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (154,12,'TA','DERMAGA SISI UTARA',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (155,12,'DSS','DERMAGA SSU',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (156,12,'DTM','DERMAGA TM',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (157,12,'DBNW','DERMAGA BNWM',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (158,12,'DBMM','DERMAGA BMM',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (159,12,'DBN','DERMAGA BANDAR N',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (160,12,'DCS','DERMAGA CHIU SHIH',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (161,12,'DMA','DERMAGA MINA A',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (162,12,'DJK','DERMAGA JK',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (163,12,'DII','DERMAGA BARAT II',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (164,12,'DKM','DERMAGA KUALA M',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (165,12,'1','DERMAGA TIMUR',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (166,12,'DBK','DERMAGA BHUWANA K',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (167,12,'DIII','DERMAGA BARAT III',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (168,12,'DJBB','DERMAGA JBB',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (169,12,'DBTS','DERMAGA BTS',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (170,12,'DSBU','DERMAGA SBU',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (171,12,'DDAB','DERMAGA DAB',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (172,12,'DTKF','DERMAGA TKF',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (173,12,'DIM','DERMAGA INTI M',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (174,12,'MRN','DERMAGA MARINA',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (175,12,'99','DERMAGA LAIN',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (176,12,'PT2','DERMAGA PERTAMINA (LABUH)',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (177,12,'FJ','FLOATING JETTY',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (178,12,'7','DERMAGA CELUKAN BAWANG',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (179,12,'OBCB','OUTER BOUY CELUKAN BAWANG',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (180,29,'23','DMG UMUM KUALA PEMBUANG',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (181,29,'1','DERMAGA UMUM',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (182,29,'2','DERMAGA KHUSUS',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (183,29,'3','PERTAMINA',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (184,29,'4','PT.SAMPIT',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (185,29,'RT','LOADING POINT SAMPIT',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (186,29,'6','AMBANG LUAR',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (187,29,'7','INDOBALAMBIT. PT',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (188,29,'8','RDS DERMAGA',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (189,15,'DN II','DERMAGA NUSANTARA II',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (190,15,'DL','DERMAGA LOKAL',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (191,15,'DR','DERMAGA RAKYAT',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (192,15,'MB','MORING BUOY INDOCEMENT',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (193,15,'RD','REDE',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (194,15,'05MB','REDE MBY',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (195,15,'DN I','DERMAGA NUSANTARA I',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (196,29,'9','PHM.PT',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (197,29,'22','TERAWAN / K.PEMBUANG',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (198,29,'11','REDE',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (199,29,'12','PT.PERKASAWANA',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (200,29,'13','DERMAGA MULTIPURSP BAGENDANG 1',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (201,29,'14','REDE D. UMUM',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (202,29,'15','REDE DERSUS',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (203,29,'16','DERMAGA CURAH CAIR BAGENDANG',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (204,29,'RT30','LOADING POINT KUALA PEMBUANG',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (205,29,'26','DERMAGA UMUM PAGATAN',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (206,29,'27','DERMAGA KHUSUS PAGATAN',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (207,29,'RT33','LOADING POINT PAGATAN',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (208,29,'31','DERMAGA UMUM SAMUDA',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (209,29,'32','PINGGIRAN SAMUDA',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (210,29,'17','DMG. KHUSUS HAJI SYECH',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (211,29,'18','DMG. KHUSUS PT. MAKIN',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (212,29,'19','DERMAGA LLASD',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (213,29,'20','PT.RAJAWALI',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (214,29,'24','ADJ SAMPIT',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (215,29,'25','DERMAGA LABEHU SAMPIT',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (216,29,'28','DKL (DERMAGA KHUSUS LIAR)',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (217,29,'29','DMG SAMPAGA RAYA',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (218,29,'30','REDE PELB BAGENDANG',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (219,29,'36','DERMAGA PUNDI',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (220,18,'3','PELRA',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (221,18,'5','JETTY PERTAMINA',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (222,18,'6','TENDER',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (223,18,'BC','BEACHING',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (224,18,'1','LOKAL',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (225,18,'7','ANGKATAN LAUT',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (226,18,'2','NUSANTARA',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (227,18,'8','MULTIGUNA',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (228,18,'10','MULTIPURPOSE (EKS PELRA)',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (229,18,'26','DERMAGA PELABUHAN IPI',20);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (230,18,'25','DERMAGA PELABUHAN ENDE',20);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (231,18,'9','JETTY PLTU',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (232,18,'23','NUSANTARA WPU',19);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (233,18,'2302','PELRA WPU',19);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (234,18,'22','NUSANTARA 1 KBI',34);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (235,18,'2202','NUSANTARA 2 KBI',34);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (236,24,'50','DUKS PULPIS',27);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (237,31,'15','EXPLOITASI ENERGI INDONESIA',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (238,31,'3','DERMAGA UMUM KUMAI',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (239,31,'4','DERMAGA UMUM (P)',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (240,31,'6','DERMAGA PT.SAP',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (241,31,'1','OB KUMAI',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (242,31,'7','DERMAGA INDOTRUBA TENGAH',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (243,31,'8','DERMAGA WANA SAWIT',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (244,31,'2','DERMAGA UMUM BUMI HARJO',34);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (245,31,'5','DERMAGA PERTAMINA',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (246,31,'9','REDE PINGGIRAN',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (247,31,'12','DU',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (248,31,'10','DERMAGA BW PLANTATION',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (249,31,'13','DERMAGA KAPUAS PRIMA COAL',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (250,31,'14','DERMAGA KORINTIGA HUTANI',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (251,31,'16','DERMAGA UMUM PANGKALAN BUN',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (252,31,'20','DERMAGA KORINDO PANGKALAN BUN',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (253,31,'21','SUNGAI RANGIT',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (254,31,'22','KALIMANTAN SAWIT KUSUMA',34);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (255,31,'27','DERMAGA MULTIPURPOSE BUMIHARJO',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (256,31,'28','DERMAGA CURAH CAIR 1 BUMIHARJO',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (257,31,'24','DERMAGA CITRA BORNEO CENTER',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (258,31,'17','DERMAGA UMUM SUKAMARA',35);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (259,31,'18','DERMAGA UMUM (P) PANGKALAN BUN',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (260,31,'19','DERMAGA UMUM (P) SUKAMARA',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (261,31,'23','DERMAGA PUTRA BALI',34);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (262,31,'25','OB PANGKALAN BUN',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (263,31,'26','OB SUKAMARA',32);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (264,31,'29','DERMAGA CURAHCAIR BUMIHARJO J2',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (265,31,'30','DERMAGA JETTY 3 BUMIHARJO',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (266,31,'11','DU (P)',31);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (267,25,'26','REDE GOLDEN HOPE',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (268,25,'25','REDE PERTAMINA',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (269,14,'1','DERMAGA I',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (270,14,'2','DERMAGA II',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (271,14,'3','DERMAGA III',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (272,5,'2','DERMAGA UMUM',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (273,5,'1','DERMAGA REDE',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (274,5,'3','DUKS',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (275,5,'4','DERMAGA UMUM',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (276,12,'OBDUKS','OUTER BUOY DUKS',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (277,7,'10','REDE KHUSUS',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (278,7,'2','REDE UMUM',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (279,2,'75','TUKS BEN SANTOSA',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (280,18,'31','REDE WAINGAPU',19);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (281,24,'26','KADE J.JAYA',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (282,24,'27','KADE KATAN PRIMA PERMAI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (283,24,'28','KADE UNITED TRAKTOR',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (284,24,'29','KADE W.T.U/WIJAYA',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (285,24,'30','KADE HENDRATNA',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (286,24,'31','KADE AUSTRAL BYNA',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (287,24,'32','KADE GUNUNG MERANTI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (288,24,'34','KADE IWCI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (289,24,'46','KADE SURYA SATRIA TC',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (290,24,'48','PINGGIRAN',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (291,24,'5','DERMAGA 50',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (292,24,'TRS2','TRISAKTI 200',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (293,24,'TRS1','TRISAKTI 100',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (294,24,'TRS3','TRISAKTI 300',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (295,24,'TRS4','TRISAKTI 400',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (296,24,'TRS5','TRISAKTI 500',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (297,24,'TPKB1','TPKB CC1',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (298,24,'TPBK2','TPKB CC2',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (299,24,'20','PELRA BASIRIH',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (300,24,'21','PELRA MARTAPURA BARU',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (301,24,'22','PELRA MARTAPURA LAMA',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (302,7,'8','DUKS BOSOWA',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (303,7,'3','DUKS PUSRI',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (304,7,'4','DUKS PERTAMINA',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (305,7,'5','DUKS SUMITAMA',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (306,7,'1','DERMAGA UMUM',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (307,7,'7','DERMAGA LANAL BANYUWANGI',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (308,7,'6','DUKS SEMEN GRESIK',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (309,17,'18','DMG KSOP NUSANTARA',17);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (310,9,'3','REDE DALAM',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (311,9,'4','PELABUHAN COASTER',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (312,9,'5','PELABUHAN DALAM',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (313,9,'8','GUDANG 16 (WKC)',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (314,9,'9','JNL EX PLB NELAYAN',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (315,9,'10','KBT',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (316,9,'12','KBB S/D TIRTARIA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (317,9,'13','DUKS DWIMATAMA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (318,9,'14','KADE KHUSUS PLTU / CBM',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (319,9,'15','PERTAMINA JETTY',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (320,9,'16','DERMAGA CPO',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (321,9,'17','DOCK PENGERUKAN / JMI-II',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (322,9,'18','BOOM KECIL',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (323,9,'19','PERTAMINA / SBM',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (324,9,'20','DOCK JMI',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (325,9,'21','DOCK KOJA BHR',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (326,9,'22','DOCK JWTS',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (327,9,'23','SBM',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (328,9,'25','DERMAGA SAMUDERA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (329,9,'26','BOUY SAMUDERA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (330,9,'27','TPKS',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (331,9,'31','SRIBOGA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (332,9,'32','DOLPHIN ANTARA PUSRI SRIBOGA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (333,9,'40','KLI',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (334,9,'42','PLTU',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (335,9,'7','ANTARA PLBH. DALAM I DAN II',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (336,9,'1','LAUT',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (337,9,'2','REDE LUAR',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (338,9,'50','DERMAGA DISTRIK NAVIGASI',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (339,9,'33','INDOPROMA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (340,9,'51','TANJUNG JATI',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (341,9,'34','DERMAGA CURAH CAIR',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (342,9,'43','DERMAGA OPSICO',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (343,7,'9','DUKS BOSOWA GAS',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (344,3,'2','DERMAGA KALIANGET',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (345,3,'13','TERMINAL CRH KERING/LOGS (GJT)',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (346,3,'22','DERMAGA 70',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (347,3,'23','DERMAGA 265',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (348,3,'25','DERMAGA TALUD TEGAK 1',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (349,3,'26','DERMAGA PELRA',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (350,3,'33','IBL SISI LUAR',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (351,3,'4','DERMAGA 78',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (352,3,'5','MULTIPURPOSE',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (353,3,'21','DERMAGA BANGUN ARTA',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (354,3,'14','TERMINAL MULTIPURPOSE (GJT)',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (355,2,'90','ZONA LABUH 2 (SURABAYA)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (356,2,'91','ZONA LABUH 3 (SURABAYA)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (357,2,'92','ZONA LABUH 5 (AMBANG LUAR)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (358,2,'93','ZONA LABUH 6 (AMBANG LUAR)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (359,2,'32','MIRAH SELATAN',2);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (360,2,'39','LAMONG CURAH KERING',10);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (361,2,'42','KALIMAS-DERMAGA KM',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (362,2,'43','KALIMAS-DERMAGA KLM',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (363,2,'53','SEMAMPIR DERMAGA BARAT',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (364,3,'30','DERMAGA TALUD TEGAK',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (365,3,'31','DERMAGA TALUD TEGAK SISI DALAM',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (366,3,'34','DERMAGA UMUM PENUMPANG',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (367,25,'28','DERMAGA BATULICIN 2',52);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (368,31,'31','DERMAGA CURAH CAIR 2 BUMIHARJO',33);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (369,15,'MB I','MOORING BUOY BOSOWA',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (370,7,'12','ALUR SELATAN',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (371,7,'11','ALUR UTARA',7);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (372,18,'30','REDE KALABAHI',34);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (373,11,'38','REDE DUKS',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (374,11,'33','REDE UMUM',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (375,9,'52','SHIP TO SHIP',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (376,9,'53','QUARANTINE SHIP',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (377,9,'54','EMERGENCY',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (378,25,'27','DERMAGA BORNEO INDOBARA',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (379,17,'23','DMG LCT BADAS',16);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (380,9,'55','KAPAL B3, KAPAL TANKER, KAPAL',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (381,9,'56','NO ANCHORAGE AREA',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (382,25,'OBS','OUTBAR SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (383,25,'S04','DERMAGA 4 SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (384,1,'18','NILAM UTARA',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (385,25,'T2','JETTY SMART T2',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (386,25,'T1','JETTY SMART T 1',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (387,25,'S6','JETTY SMART S6',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (388,25,'S5','JETTY SMART S5',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (389,25,'S4','JETTY SMAR S4',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (390,25,'S3','JETTY SMART S3',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (391,25,'S2','JETTY SMART S2',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (392,25,'S1','JETTY SMART S1',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (393,25,'ITP B4','JETTY ITP TARJUN B4',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (394,25,'ITP B3','JETTY ITP TARJUN B3',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (395,25,'ITP B2','JETTY ITP TARJUN B2',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (396,25,'ITP B1','JETTY ITP TARJUN B1',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (397,25,'ITP A4','JETTY ITP TARJUN A4',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (398,25,'ITP A3','JETTY ITP TARJUN A3',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (399,25,'ITP A2','JETTY ITP TARJUN A2',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (400,25,'ITP A1','JETTY ITP TARJUN A 1',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (401,25,'GHN2','JETTY GOLDEN HP 2',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (402,25,'GHN1','JETTY GOLDEN HP 1',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (403,25,'PTM2','JETTY PERTAMINA 2',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (404,25,'PTM1','JETTY PERTAMINA 1',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (405,14,'4','DERMAGA TONASA',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (406,14,'5','PINGGIRAN',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (407,9,'61','DERMAGA 1 TEGAL',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (408,9,'62','DERMAGA PELRA TEGAL',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (409,9,'63','DERMAGA PERIKANAN TEGAL',9);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (410,17,'21','DMG PELRA BIMA 2',17);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (411,17,'20','DMG PELRA BIMA 1',17);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (412,17,'22','DMG KSOP NUSANTARA BDS',16);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (413,2,'74','TUKS PERIKANAN NUSANTARA',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (414,2,'73','TUKS TIRTA WIGUNA AGUNG',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (415,2,'71','TUKS PERTAMINA GOSPIER',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (416,2,'72','TUKS TAMBANGAN JAYA',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (417,2,'69','TUKS GALANGAN SURYA PELNI',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (418,2,'68','TUKS PELINDO MARINE SERVICE',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (419,2,'67','TUKS NAJATIM',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (420,2,'66','TUKS DUMAS DOCK 2',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (421,2,'65','TUKS DUMAS DOCK 1',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (422,2,'64','TUKS DOCK DAN PERKAPALAN SBY',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (423,2,'62','TUKS DEWA RUCI AGUNG',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (424,2,'63','TUKS BOGASARI',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (425,25,'OBM','OUT BAR MEKARPUTIH',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (426,25,'M05','JETTY 2 BBM',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (427,25,'M04','JETTY 1 BBM',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (428,25,'M03','JETTY MUAT',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (429,25,'M02','JETTY SISI DALAM BONGKAR',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (430,25,'M01','JETTY SISI LUAR BONGKAR',51);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (431,2,'60','PERTAMINA ASPAL',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (432,2,'59','DERMAGA 180',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (433,2,'76','DERMAGA PELRA',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (434,2,'78','DERMAGA TALUD TEGAK 1',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (435,2,'79','DERMAGA TALUD TEGAK',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (436,2,'81','DERMAGA TALUD TEGAK SISI DALAM',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (437,3,'80','IBL SISI DALAM',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (438,24,'53','AMBANG LUAR',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (439,17,'17','DMG BIMA',17);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (440,17,'16','DMG BADAS',16);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (441,5,'1','DERMAGA UMUM PASURUAN',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (442,15,'OB','OUTER BUOY',NULL);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (443,18,'13','PERTAMINA',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (444,24,'1','BOUY LUAR',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (445,24,'3','REDE TRISAKTI',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (446,25,'S01','DERMAGA 1 SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (447,25,'S02','DERMAGA 2 SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (448,25,'S03','DERMAGA 3 SATUI',53);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (449,24,'6','REDE PULAU KUIN',24);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (450,3,'36','WILMAR KADE',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (451,3,'12','PERTAMINA ASPAL',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (452,3,'11','PLTGU GRESIK',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (453,3,'10','SEMEN GRESIK',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (454,3,'9','PETROKIMIA',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (455,3,'8','MASPION',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (456,3,'7','SMELTING',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (457,12,'4','DERMAGA SELATAN 02 CELUK',12);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (458,21,'5','AREA LABUH ENDE',20);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (459,21,'1','AREA LABUH',21);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (460,21,'2','DERMAGA I',21);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (461,21,'3','DERMAGA II',21);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (462,21,'4','DERMAGA III',21);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (463,21,'IPI','DERMAGA PELABUHAN IPI',20);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (464,21,'ENDE','DERMAGA PELABUHAN ENDE',20);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (465,29,'37','DERMAGA MULTIPURSP BAGENDANG 2',29);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (466,17,'19','DMG KSOP PELRA',16);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (467,2,'18','NILAM UTARA',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (468,14,'7','AREA REDE',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (469,14,'6','LAUT',14);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (470,1,'OB','OUTER BUOY',NULL);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (471,15,'ASDP','DMG ASDP',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (472,2,'61','TUKS BEN SENTOSA',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (473,18,'12','REDE',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (474,18,'11','POB',18);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (475,11,'40','MULTIPURPOSE II',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (476,11,'39','MULTIPURPOSE 1',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (477,25,'STG04','STAGEN JETTY 4',62);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (478,25,'STG3','STAGEN JETTY 3',62);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (479,25,'STG2','STAGEN JETTY 2',62);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (480,25,'STG1','STAGEN JETTY 1',62);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (481,25,'STS','STS KOTABARU',25);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (482,3,'94','AREA LABUH SHIP TO SHIP (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (483,3,'95','AREA QUARANTINE SHIP (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (484,3,'96','AREA LABUH EMERGENCY (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (485,3,'97','AREA LABUH KAPAL B3 (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (486,3,'98','AREA LABUH NO ANCHORAGE (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (487,3,'99','AREA REDE LUAR/DALAM (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (488,2,'94','AREA LABUH SHIP TO SHIP (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (489,2,'95','AREA QUARANTINE SHIP (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (490,2,'96','AREA LABUH EMERGENCY (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (491,2,'97','AREA LABUH KAPAL B3 (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (492,2,'98','AREA LABUH NO ANCHORAGE (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (493,2,'99','AREA REDE LUAR/DALAM (GSK)',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (494,2,'50','TERMINAL MULTIPURPOSE (GJT)',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (495,2,'101','DERMAGA PT. JASA MULIA ABADI R',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (496,3,'101','DERMAGA PT. JASA MULIA ABADI R',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (497,15,'PN','DERMAGA PONTON',15);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (498,11,'32','PLTU 2 JATENG ADIPALA BUNTON',11);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (499,5,'5','DERMAGA PPI',5);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (500,18,'32','REDE ENDE',20);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (501,2,'45','TERMINAL CRH KERING/LOGS (GJT)',4);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (502,2,'46','TERMINAL MANYAR',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (503,2,'47','DERMAGA 70 GRESIK',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (504,2,'54','DERMAGA 78',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (505,2,'48','DABN',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (506,2,'58','DERMAGA BANGUN ARTA',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (507,2,'49','IBL SISI LUAR',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (508,2,'26','REDE DOCK PAL',8);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (509,2,'57','DERMAGA 265',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (510,2,'89','SEMEN GRESIK',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (511,2,'82','IBL SISI DALAM',3);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (512,2,'83','DERMAGA PT. KIAS',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (513,2,'84','DERMAGA PT. IMS',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (514,2,'85','DERMAGA PT. SUMBERMAS INDAH P',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (515,2,'86','DERMAGA PT. ORELA SHIPYARD',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (516,2,'87','DERMAGA PT. MITRAARTHA GEMA PE',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (517,2,'29','DERMAGA PT. BERLIAN MANYAR SEJ',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (518,3,'83','DERMAGA PT. KIAS',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (519,3,'84','DERMAGA PT. IMS',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (520,3,'85','DERMAGA PT. SUMBERMAS INDAH P',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (521,3,'86','DERMAGA PT. ORELA SHIPYARD',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (522,3,'87','DERMAGA PT. MITRAARTHA GEMA PE',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (523,3,'29','DERMAGA PT. BERLIAN MANYAR SEJ',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (524,3,'63','DERMAGA PT. DABN',6);
INSERT INTO dermaga(id,kdCabang,mdmgKode,mdmgNama,kdTerminal) VALUES (525,2,'100','KADE BENOA',2);
